/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2018-06-21 21:00:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.net.*;
import pollSystem.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("pollSystem");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset = \"utf-8\">\r\n");
      out.write("      <title>主頁</title>\r\n");
      out.write("\t  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var choiced = 0;  //接上後可忽略\r\n");
      out.write("\t\t var count = 0;    //接上後可忽略\r\n");
      out.write("\t\t var divColor = [\"#FF0088\", \"#FF0000\", \"#FF5511\", \"FF8800\", \"FFBB00\", \"FFFF00\", \"BBFF00\", \"77FF00\"];\r\n");
      out.write("\t\t var labelName = [\"main\", \"bonus\", \"entertain\", \"sport\", \"money\", \"policitic\", \"technique\", \"life\"];\r\n");
      out.write("\t\t var labelname = [\" 首頁\", \" BONUS\", \" 娛樂\", \" 運動\", \" 財經\", \" 政治\", \" 科技\", \" 生活\"];\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //左邊label動作\r\n");
      out.write("\t\t function labelChange(i)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t//改label顏色\r\n");
      out.write("\t\t\tfor(var j = 0 ; j < 8; j++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.getElementById(labelName[j]).setAttribute(\"class\", \"nchoicedL\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(labelName[i]).setAttribute(\"class\", \"choicedL\");\r\n");
      out.write("\t\t\t//此處呼叫servlet 轉至相應類別\r\n");
      out.write("\t\t\tchoiced = i; //接上後可忽略\r\n");
      out.write("\t\t\tdocument.title = \"主頁 - \" + labelname[i];\r\n");
      out.write("\t\t\tconsole.log(\"change to \" + labelname[i]);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //新增標題\r\n");
      out.write("\t\t function addQ()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tvar i = 200 + (200 + 5) * count;  //間距\r\n");
      out.write("\t\t\t//測試內容\r\n");
      out.write("\t\t\tvar image = \"img/img.png\"\r\n");
      out.write("\t\t\tvar title = \"tesssssssssssssssssst titllllllllllllllle\"\r\n");
      out.write("\t\t\tvar link = \"https://google.com\";\r\n");
      out.write("\t\t\tvar content = \"123?123?123?123?123?123?123?123?123?123?123?123?123?123?123?123?123?123?123?123?123?\";\r\n");
      out.write("\t\t\t//此處加入標題 連結 圖片\r\n");
      out.write("\t\t\tdocument.getElementById( \"ContentDiv\" ).innerHTML += \"<div class = 'contentDiv' style = 'top : \" + i + \"px;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  + \"<img src = \" + image + \" class = 'contentDI'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  + \"<div class = 'contentDD'><div class ='contentDDT'>\" + title + \"</div><div class='contentDDC'>\" + content + \"</div></div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  + \"<a href = \" + link + \"><button type='button' class = 'contentDB'>填寫問卷</button></a>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  + \"</div>\";\r\n");
      out.write("\t\t\tcount++; //接上後可忽略\r\n");
      out.write("\t\t\tconsole.log(\"add\");\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //新增填寫紀錄\r\n");
      out.write("\t\t function addH()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tvar test = \"測試這他媽的區塊能塞多少個字\";\r\n");
      out.write("\t\t\tvar testlink = \"https://google.com\";\r\n");
      out.write("\t\t\t//加入填寫紀錄\r\n");
      out.write("\t\t\tdocument.getElementById( \"browsDD\" ).innerHTML += \"<a href = \" + testlink + \" style = 'text-decoration: none;'><p class = 'browsS'>\" + test + \"</p></a>\";\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //搜尋標題\r\n");
      out.write("\t\t function searchClick()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tvar x = document.getElementById( \"inputL\" ).value;\r\n");
      out.write("\t\t\t//呼叫servlet\r\n");
      out.write("\t\t\tdocument.location.href = \"https://google.com/search?q=\" + x;\r\n");
      out.write("\t\t\tconsole.log(\"click\");\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //載入個人資訊\r\n");
      out.write("\t\t function setinfo()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t//此處載入圖片跟內容\r\n");
      out.write("\t\t\t//document.getElementById( \"infoDD\" ).;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //載入熱門關鍵字\r\n");
      out.write("\t\t function setWord()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t//var word = \"test\";\r\n");
      out.write("\t\t\tvar link = \"https://google.com/\";\r\n");
      out.write("\t\t\tdocument.getElementById( \"undersearch\" ).innerHTML = \"推薦關鍵字 :\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   + \"&nbsp<a href = '\" + link + \"search?q=世足\" + \"' target = 'blink' style = 'text-decoration: none;'><red>世足</red>.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   + \"&nbsp<a href = '\" + link + \"search?q=俄羅斯\" + \"' target = 'blink' style = 'text-decoration: none;'><red>俄羅斯</red>.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   + \"&nbsp<a href = '\" + link + \"search?q=旅遊\" + \"' target = 'blink' style = 'text-decoration: none;'><red>旅遊</red>.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   + \"&nbsp<a href = '\" + link + \"search?q=NBA\" + \"' target = 'blink' style = 'text-decoration: none;'><red>NBA</red>\";\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t function testQ()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tvar countt = Math.floor(Math.random()*20)+1;\r\n");
      out.write("\t\t\tfor(var i = 1; i < countt; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\taddQ();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t function testH()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tvar countt = Math.floor(Math.random()*10)+1;\r\n");
      out.write("\t\t\tfor(var i = 1; i < countt; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\taddH();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //網頁起始設定\r\n");
      out.write("         function start()\r\n");
      out.write("         {\r\n");
      out.write("\t\t\t//改上面圖片 做好玩的\r\n");
      out.write("            var x = Math.floor(Math.random()*5)+1;\r\n");
      out.write("\t\t\tdocument.getElementById( \"image\" ).setAttribute(\"style\", \"background-image: url('img/\" + x + \".jpg');\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//依解析度改位置\r\n");
      out.write("\t\t\tvar w = (screen.width - 450)/2-50;\r\n");
      out.write("\t\t\tdocument.getElementById( \"searchD\" ).setAttribute(\"style\", \"margin-left:\" + w + \"px;\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//抓熱門關鍵字  (痾，這先放著吧)\r\n");
      out.write("\t\t\tsetWord();\r\n");
      out.write("\t\t\t//要設定個人資訊 setinfo()\r\n");
      out.write("         }\r\n");
      out.write("\t\t \r\n");
      out.write("         window.addEventListener( \"load\", start, false );\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //回到最上層\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t//動畫方式回到上層\r\n");
      out.write("\t\t$(\"#gotopD\").click(function(){\r\n");
      out.write("\t\t\tjQuery(\"html,body\").animate({scrollTop:0},300);\r\n");
      out.write("\t\t\t//jQuery(\"html,body\").animate({scrollTop: $(\"#labelD\").offset().top},300);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//目前的位置距離網頁頂端，若大於300px則顯示回上層圖示;否則隱藏\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tif ( $(this).scrollTop() > 500){\r\n");
      out.write("\t\t\t\t$('#gotopD').fadeIn(\"fast\");\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$('#gotopD').stop().fadeOut(\"fast\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("      </script>\r\n");
      out.write("\t  <style>\r\n");
      out.write("\t\tbody\t{\r\n");
      out.write("\t\t\t\t\tfont-family: Helvetica, Microsoft YaHei, LiHei Pro, TW-Kai;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*熱門關鍵字*/\r\n");
      out.write("\t\t#undersearch {\r\n");
      out.write("\t\t\t\t\tfont-size: 17px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#undersearch red {\r\n");
      out.write("\t\t\t\t\tcolor: red;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*搜尋Div*/\r\n");
      out.write("\t\t#searchD {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\t\ttop: 1%;\r\n");
      out.write("\t\t\t\t\twidth: 450px;\r\n");
      out.write("\t\t\t\t\theight: 150px;\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("\t\t\t\t\tpadding: 5px 5px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 20px;  /*圓角*/\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*搜尋條*/\r\n");
      out.write("\t\t.searchL {\r\n");
      out.write("\t\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*左邊Div*/\r\n");
      out.write("\t\t#labelD\t{\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 25%;\r\n");
      out.write("\t\t\t\t\tleft: 6%;\r\n");
      out.write("\t\t\t\t\twidth: 7%;\r\n");
      out.write("\t\t\t\t\theight: 470px;\r\n");
      out.write("\t\t\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\t\t\tpadding: 5px 5px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;  /*圓角*/\r\n");
      out.write("\t\t\t\t\tbox-shadow:4px 3px 2px 1px #A42D00;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*已選標籤*/\r\n");
      out.write("\t\t.choicedL  {\r\n");
      out.write("\t\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\t\tcolor: #FF0000;\r\n");
      out.write("\t\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*未選標籤*/\r\n");
      out.write("\t\t.nchoicedL {\r\n");
      out.write("\t\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\t\tcolor: #5599FF;\r\n");
      out.write("\t\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*中間Div*/\r\n");
      out.write("\t\t.contentDiv {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\tleft: 18%;\r\n");
      out.write("\t\t\t\t\twidth: 50%;\r\n");
      out.write("\t\t\t\t\theight: 160px;\r\n");
      out.write("\t\t\t\t\tmargin-bottom: 50px;\r\n");
      out.write("\t\t\t\t\tbackground-color: #FFFFFF; \r\n");
      out.write("\t\t\t\t\tbox-shadow:4px 3px 2px 1px black;\r\n");
      out.write("\t\t\t\t\tpadding: 5px 5px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDI {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 15px;\r\n");
      out.write("\t\t\t\t\tleft: 25px;\r\n");
      out.write("\t\t\t\t\theight: 120px;\r\n");
      out.write("\t\t\t\t\twidth: 120px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDD {\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(48, 191, 179, 0.61);\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 15px;\r\n");
      out.write("\t\t\t\t\tleft: 160px;\r\n");
      out.write("\t\t\t\t\theight: 130px;\r\n");
      out.write("\t\t\t\t\twidth: 65%;\r\n");
      out.write("\t\t\t\t\tpadding: 5px 5px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDDT {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop:3%;\r\n");
      out.write("\t\t\t\t\tleft:3%;\r\n");
      out.write("\t\t\t\t\twidth:98%;\r\n");
      out.write("\t\t\t\t\theight: 35px;\r\n");
      out.write("\t\t\t\t\tfont-size: 30px;\r\n");
      out.write("\t\t\t\t\tcolor: blue;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDDC {\r\n");
      out.write("\t\t\t\t\tmargin-top: 15px;\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop:35%;\r\n");
      out.write("\t\t\t\t\tleft:3%;\r\n");
      out.write("\t\t\t\t\twidth: 98%;\r\n");
      out.write("\t\t\t\t\theight: 75%;\r\n");
      out.write("\t\t\t\t\tfont-size: 15px;\r\n");
      out.write("\t\t\t\t\tcolor: gray;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDB {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 72%;\r\n");
      out.write("\t\t\t\t\tleft: 88%;\r\n");
      out.write("\t\t\t\t\tpadding: 8px 8px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\t\tbackground-color: #BBFF66;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDB:hover {\r\n");
      out.write("\t\t\t\t\tborder: 1px solid #ffffff;\r\n");
      out.write("\t\t\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*上圖*/\r\n");
      out.write("\t\t.background1  {\r\n");
      out.write("\t\t\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\t\t\tbackground-attachment: scroll;\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 0%;\r\n");
      out.write("\t\t\t\t\tleft: 0%;\r\n");
      out.write("\t\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\t\theight: 40%;\r\n");
      out.write("\t\t\t\t\tz-index: -998;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*中下底*/\r\n");
      out.write("\t\t.background2 {\r\n");
      out.write("\t\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\t\ttop: 0%;\r\n");
      out.write("\t\t\t\t\tleft: 0%;\r\n");
      out.write("\t\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\t\tz-index: -999;\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(62, 173, 97, 0.63);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*個人資訊*/\r\n");
      out.write("\t\t#infoD\t{\r\n");
      out.write("\t\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\t\ttop: 30%;\r\n");
      out.write("\t\t\t\t\tright: -485px;  /*設置水平位置，依所放的內容多寡需要自行手動調整*/\r\n");
      out.write("\t\t\t\t\twidth: 500px;\r\n");
      out.write("\t\t\t\t\theight: 350px;\r\n");
      out.write("\t\t\t\t\tbackground: #FFCC22;  /*背景顏色*/\r\n");
      out.write("\t\t\t\t\tpadding: 10px 20px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;  /*圓角*/\r\n");
      out.write("\t\t\t\t\tmargin-top: -50px;\r\n");
      out.write("\t\t\t\t\t-webkit-transition:right 0.6s;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#infoD:hover{  /*當滑鼠移至此區塊時，伸縮區塊*/\r\n");
      out.write("\t\t\t\t\tright: 10px;\r\n");
      out.write("\t\t\t\t\t-webkit-transition: 0.6s;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#infoD #title{\r\n");
      out.write("\t\t\t\t\tpadding-right: 5px;  /*讓標題與連結中間有空隙*/\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#infoT  {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 70%;\r\n");
      out.write("\t\t\t\t\tleft: 4%;\r\n");
      out.write("\t\t\t\t\twidth: 11px;\r\n");
      out.write("\t\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*資訊黑背景*/\r\n");
      out.write("\t\t#infoDD {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("\t\t\t\t\ttop: 2%;\r\n");
      out.write("\t\t\t\t\tleft: 55px;\r\n");
      out.write("\t\t\t\t\twidth: 80%;\r\n");
      out.write("\t\t\t\t\theight: 330px;\r\n");
      out.write("\t\t\t\t\tpadding: 10px 20px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;  /*圓角*/\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#gotopD {\r\n");
      out.write("\t\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\t\ttop: 92%;\r\n");
      out.write("\t\t\t\t\tleft: 90%;\r\n");
      out.write("\t\t\t\t\theight: 20px;\r\n");
      out.write("\t\t\t\t\twidth: 22px;\r\n");
      out.write("\t\t\t\t\tmargin-right: 200px;\r\n");
      out.write("\t\t\t\t\tbackground: rgba(0, 0, 0, 0.6);\r\n");
      out.write("\t\t\t\t\tpadding: 10px 20px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;  /*圓角*/\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#gotopP {\r\n");
      out.write("\t\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*瀏覽紀錄*/\r\n");
      out.write("\t\t#browsD {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 28%;\r\n");
      out.write("\t\t\t\t\tleft: 74%;\r\n");
      out.write("\t\t\t\t\twidth: 15%;\r\n");
      out.write("\t\t\t\t\theight: 470px;\r\n");
      out.write("\t\t\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\t\t\tpadding: 5px 5px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\t\tbox-shadow:4px 3px 2px 1px #0044BB;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#browsP:hover {\r\n");
      out.write("\t\t\t\t\tcursor: default;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#browsDD {\r\n");
      out.write("\t\t\t\t\toverflow-y: auto;\r\n");
      out.write("\t\t\t\t\toverflow-x; auto;\r\n");
      out.write("\t\t\t\t\theight: 85%;\r\n");
      out.write("\t\t\t\t\twidth: 96%;\r\n");
      out.write("\t\t\t\t\tmargin-left: 10px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.browsS {\r\n");
      out.write("\t\t\t\t\twidth: 99%;\r\n");
      out.write("\t\t\t\t\tfont-size: 17px;\r\n");
      out.write("\t\t\t\t\tcolor: #0066FF;\r\n");
      out.write("\t\t\t\t\tpadding: 2px 2px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.browsS:hover {\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(128, 128, 128, 0.5);\r\n");
      out.write("\t\t\t\t\tcolor: red;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t    .loginOutButton {\r\n");
      out.write("            width: 125px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .getRewardButton {\r\n");
      out.write("            width: 125px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            //top: 92px;\r\n");
      out.write("\t\t\tmargin-top: 20px;\r\n");
      out.write("\t\t\tmargin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .headImg {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 220px;\r\n");
      out.write("        }\r\n");
      out.write("        .nchoicedL:hover {\r\n");
      out.write("\t        cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.loginOutButton:hover {\r\n");
      out.write("\t\t    cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.getRewardButton:hover {\r\n");
      out.write("\t\t  \tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#searchButton:hover {\r\n");
      out.write("\t\t    cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.loginInButton:hover {\r\n");
      out.write("\t\t    cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.singInButton:hover {\r\n");
      out.write("\t\t    cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.\r\n");
      out.write("\t  </style>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("\t<div id = \"image\" class = \"background1\"></div>\r\n");
      out.write("\t<div class = \"background2\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"searchD\">\r\n");
      out.write("\t  <br>\r\n");
      out.write("      <form action = \"KeywordSearchServlet\" method = \"post\">\r\n");
      out.write("         <p align = \"center\">\r\n");
      out.write("\t\t\t<label class = \"searchL\">問天&nbsp&nbsp&nbsp\r\n");
      out.write("\t\t\t\t<input id = \"inputL\" name=\"keyword\" type = \"text\" class = \"searchL\" placeholder = \"輸入你想搜尋的標題...\">\r\n");
      out.write("\t\t\t\t<input id = \"searchButton\" type = \"submit\" value = \"Search\" class = \"searchL\">\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<label id = \"undersearch\">\r\n");
      out.write("\t\t\t<!--要加東西-->\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t </p>\r\n");
      out.write("      </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"labelD\">\r\n");
      out.write("\t\t<!--寫入左邊標籤-->\r\n");
      out.write("\t\t");

			int type = (int) request.getSession().getAttribute("TYPE");
			//int typen = 0;
			//typen = Integer.parseInt(type);
			switch(type)
			{
				case(-1):
					out.print("<p align = 'center'><label class = 'choicedL'>&nbsp首頁</label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=0' style = 'text-decoration: none;'>&nbspBonus</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=1' style = 'text-decoration: none;'>&nbsp娛樂</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=2' style = 'text-decoration: none;'>&nbsp運動</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=3' style = 'text-decoration: none;'>&nbsp財經</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=4' style = 'text-decoration: none;'>&nbsp政治</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=5' style = 'text-decoration: none;'>&nbsp科技</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=6' style = 'text-decoration: none;'>&nbsp生活</a></label></p>");
					break;
				case(0):
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=-1' style = 'text-decoration: none;'>&nbsp首頁</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'choicedL'>&nbspBonus</label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=1' style = 'text-decoration: none;'>&nbsp娛樂</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=2' style = 'text-decoration: none;'>&nbsp運動</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=3' style = 'text-decoration: none;'>&nbsp財經</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=4' style = 'text-decoration: none;'>&nbsp政治</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=5' style = 'text-decoration: none;'>&nbsp科技</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=6' style = 'text-decoration: none;'>&nbsp生活</a></label></p>");
					break;
				case(1):
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=-1' style = 'text-decoration: none;'>&nbsp首頁</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=0' style = 'text-decoration: none;'>&nbspBonus</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'choicedL'>&nbsp娛樂</label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=2' style = 'text-decoration: none;'>&nbsp運動</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=3' style = 'text-decoration: none;'>&nbsp財經</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=4' style = 'text-decoration: none;'>&nbsp政治</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=5' style = 'text-decoration: none;'>&nbsp科技</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=6' style = 'text-decoration: none;'>&nbsp生活</a></label></p>");
					break;
				case(2):
				    out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=-1' style = 'text-decoration: none;'>&nbsp首頁</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=0' style = 'text-decoration: none;'>&nbspBonus</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=1' style = 'text-decoration: none;'>&nbsp娛樂</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'choicedL'>&nbsp運動</label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=3' style = 'text-decoration: none;'>&nbsp財經</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=4' style = 'text-decoration: none;'>&nbsp政治</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=5' style = 'text-decoration: none;'>&nbsp科技</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=6' style = 'text-decoration: none;'>&nbsp生活</a></label></p>");
				    break;
				case(3):
				    out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=-1' style = 'text-decoration: none;'>&nbsp首頁</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=0' style = 'text-decoration: none;'>&nbspBonus</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=1' style = 'text-decoration: none;'>&nbsp娛樂</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=2' style = 'text-decoration: none;'>&nbsp運動</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'choicedL'>&nbsp財經</label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=4' style = 'text-decoration: none;'>&nbsp政治</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=5' style = 'text-decoration: none;'>&nbsp科技</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=6' style = 'text-decoration: none;'>&nbsp生活</a></label></p>");
				    break;
				case(4):
				    out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=-1' style = 'text-decoration: none;'>&nbsp首頁</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=0' style = 'text-decoration: none;'>&nbspBonus</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=1' style = 'text-decoration: none;'>&nbsp娛樂</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=2' style = 'text-decoration: none;'>&nbsp運動</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=3' style = 'text-decoration: none;'>&nbsp財經</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'choicedL'>&nbsp政治</label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=5' style = 'text-decoration: none;'>&nbsp科技</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=6' style = 'text-decoration: none;'>&nbsp生活</a></label></p>");
				    break;
				case(5):
				    out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=-1' style = 'text-decoration: none;'>&nbsp首頁</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=0' style = 'text-decoration: none;'>&nbspBonus</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=1' style = 'text-decoration: none;'>&nbsp娛樂</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=2' style = 'text-decoration: none;'>&nbsp運動</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=3' style = 'text-decoration: none;'>&nbsp財經</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=4' style = 'text-decoration: none;'>&nbsp政治</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'choicedL'>&nbsp科技</label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=6' style = 'text-decoration: none;'>&nbsp生活</a></label></p>");
				    break;
				case(6):
				    out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=-1' style = 'text-decoration: none;'>&nbsp首頁</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=0' style = 'text-decoration: none;'>&nbspBonus</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=1' style = 'text-decoration: none;'>&nbsp娛樂</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=2' style = 'text-decoration: none;'>&nbsp運動</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=3' style = 'text-decoration: none;'>&nbsp財經</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=4' style = 'text-decoration: none;'>&nbsp政治</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'nchoicedL'><a href = 'PollServlet?type=5' style = 'text-decoration: none;'>&nbsp科技</a></label></p><hr>");
					out.print("<p align = 'center'><label class = 'choicedL'>&nbsp生活</label></p>");
				    break;
			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--新增標題塊的地方-->\r\n");
      out.write("\t<div id = \"ContentDiv\">\r\n");
      out.write("\t\t");

		
			ArrayList<Polls> displayPoll = (ArrayList<Polls>)request.getAttribute("displayPoll");
			int count = 0;
			int i = 0;
			String image = "img/img.png";
			
			if(displayPoll!=null){
			
				for(Polls a : displayPoll)
				{
					String str = a.getTitle();

					
		        	str=java.net.URLEncoder.encode(str);
		        	
		        	i = 200 + (200 + 5) * count;
					out.print("<div class = 'contentDiv' style = 'top : " + i + "px;'>"
							+ "<img src = " + image + " class = 'contentDI'>"
							+ "<div class = 'contentDD'><div class ='contentDDT'>" + a.getTitle() + "</div><div class='contentDDC'>" + a.getDescription() + "</div></div>"
							+ "<a href = BrowseRecordServlet?title=" +str +"&url=ShowPollServlet?id="+a.getID() + "><button type='button' class = 'contentDB'>進入問卷</button></a>"
							+ "</div>");
					
					count++;
				}
			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"browsD\">\r\n");
      out.write("\t\t<p id = \"browsP\" align = \"center\">填寫紀錄</p>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<!--新增紀錄的地方-->\r\n");
      out.write("\t\t<div id = \"browsDD\">\r\n");
      out.write("\t\t");

			ArrayList<String> browseRecord = (ArrayList<String>)request.getSession().getAttribute("browseRecord");
			if(browseRecord != null)
			{
				for(String a : browseRecord)
				{
					out.print(a);
				}
			}
		
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"infoD\">\r\n");
      out.write("\t\t<span id=\"title\"><<</span>\r\n");
      out.write("\t\t<div id = \"infoT\">會員資訊</div>\r\n");
      out.write("\t\t<!--塞會員資訊-->\r\n");
      out.write("\t\t<div id = \"infoDD\">\r\n");
      out.write("\t\t<!--判斷登入狀態-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<table \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			String loginInMessage=(String)request.getSession().getAttribute("loginStatus");
			System.out.println(request.getSession().getId());
			System.out.println(loginInMessage);
			if(loginInMessage!=null && loginInMessage.equals("logIn"))
			{
				out.print("style='display: none;'");
			}
			
      out.write(" \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <img src='img/noone.jpg' class='headImg'>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <form method='post' action='loginInServlet'>\r\n");
      out.write("                                <h4>帳號:</h4>\r\n");
      out.write("                                <input type='text' class='inputText' name='accountNumber' required='required' />\r\n");
      out.write("                                <h4>密碼:</h4>\r\n");
      out.write("                                <input type='password' class=\"inputText\" name=\"password\" required='required' />\r\n");
      out.write("                                <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("                                <input type='submit' value='登入' class='loginInButton' />\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <form method='get' action='signInPage.html'>\r\n");
      out.write("                                <input type='submit' value='註冊' class='singInButton'/>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			loginInMessage=(String)request.getSession().getAttribute("loginStatus");
			if(loginInMessage==null || !loginInMessage.equals("logIn"))
			{
				out.print("style='display: none;'");
			}
			
      out.write(" \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <img src='img/noone.jpg' class='headImg'>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <form method='post' action='logoutServlet'>\r\n");
      out.write("                            <h3 style = 'margin-left: 5px;'>名稱 : <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nowUser[\"name\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h3>\r\n");
      out.write("                            <h3 style = 'margin-left: 5px;'>帳號 : <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nowUser[\"accountNumber\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h3>\r\n");
      out.write("                            <h3 style = 'margin-left: 5px;'>點數 : <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nowUser[\"point\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h3>\r\n");
      out.write("                            <input type='submit' value='登出' class='loginOutButton' style = 'margin-left: 5px;' />\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </td>\r\n");
      out.write("\t\t        </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <form method='get' action='exchangePage.jsp'>\r\n");
      out.write("                            <input type='submit' value='兌換' class='getRewardButton' />\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"gotopD\" href = \"#top\" hidden = \"true\">\r\n");
      out.write("\t\t<a href = \"#top\" id = \"gotopP\">Top</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
