/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2018-06-21 20:38:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import pollSystem.*;

public final class questionPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("pollSystem");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset = \"utf-8\">\r\n");
      out.write("      <title>問卷</title>\r\n");
      out.write("\t  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var count = 0;    //接上後可忽略\r\n");
      out.write("\t\t var countt = 0;\r\n");
      out.write("\t\t var divColor = [\"#FF0088\", \"#FF0000\", \"#FF5511\", \"FF8800\", \"FFBB00\", \"FFFF00\", \"BBFF00\", \"77FF00\"];\r\n");
      out.write("\t\t var labelName = [\"main\", \"bonus\", \"entertain\", \"sport\", \"money\", \"policitic\", \"technique\", \"life\"];\r\n");
      out.write("\t\t var labelname = [\" 首頁\", \" BONUS\", \" 娛樂\", \" 運動\", \" 財經\", \" 政治\", \" 科技\", \" 生活\"];\r\n");
      out.write("\t\t var x = \"\";\r\n");
      out.write("\t\t var y = 0;\r\n");
      out.write("\t\t var k = 0;\r\n");
      out.write("\t\t /*var questionSize=");
		 		 
			Polls b = (Polls) request.getAttribute("pollWillAnswer");
			out.print(b.getQuestionList().size());
		 
      out.write(";*/\r\n");
      out.write("\t\t //新增標題\r\n");
      out.write("\t\t function addQ()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tvar i = 300 + (200 + 5) * countt + y;  //間距\r\n");
      out.write("\t\t\tvar tt = Math.floor(Math.random()*5)+2;\r\n");
      out.write("\t\t\tconsole.log(\"add:\" + tt);\r\n");
      out.write("\t\t\t//測試內容\r\n");
      out.write("\t\t\tvar quest = \"quest\";\r\n");
      out.write("\t\t\t//此處加入標題 連結 圖片\r\n");
      out.write("\t\t\tvar ttt = 160;\r\n");
      out.write("\t\t\tif(tt>3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tttt += (tt-3) * 40;\r\n");
      out.write("\t\t\t\ty += (tt-3) * 40;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tx += \"<div class = 'contentDiv' style = 'top : \" + i + \"px; height: \" + ttt + \"px;'><div class ='contentDDT'>\" + quest + \"</div><div class='contentDDC'>\";\r\n");
      out.write("\t\t\tfor(var t = 0; t < tt; t++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tx += \"<input class = 'options' type='radio' name=\" + countt + \" value=\" + t ;\r\n");
      out.write("\t\t\t\tif(t == 0)\r\n");
      out.write("\t\t\t\t\tx += \" checked='checked'\";\r\n");
      out.write("\t\t\t\tx += \">選項\" + t + \"<br>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tx += \"</div></div>\";\r\n");
      out.write("\t\t\tconsole.log(x);\r\n");
      out.write("\t\t\t//document.getElementById( \"ContentDiv\" ).innerHTML += x;\r\n");
      out.write("\t\t\tcountt++; \r\n");
      out.write("\t\t\tk = i + ttt;\r\n");
      out.write("\t\t\tconsole.log(\"add\");\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t function test()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t    x = \"\";\r\n");
      out.write("\t\t\t//count = Math.floor(Math.random()*5)+1;\r\n");
      out.write("\t\t\tcount = 2;\r\n");
      out.write("\t\t\tx = \"<form id='form1' name='form1' action = 'AnswerServlet' method ='post'>\";\r\n");
      out.write("\t\t\tfor(var i = 1; i < count; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\taddQ();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tk += 20;\r\n");
      out.write("\t\t\tx += \"<p id = 'enterP'  style = 'top: \" + k + \"px; magrin-bottom: 30px;' align = 'center'><input type='submit' id='button' value='送出'/></p></form>\";\r\n");
      out.write("\t\t\tdocument.getElementById( \"ContentDiv\" ).innerHTML += x;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //網頁起始設定\r\n");
      out.write("         function start()\r\n");
      out.write("         {\r\n");
      out.write("\t\t\t//改上面圖片 做好玩的\r\n");
      out.write("            var x = Math.floor(Math.random()*5)+1;\r\n");
      out.write("\t\t\tdocument.getElementById( \"image\" ).setAttribute(\"style\", \"background-image: url('img/\" + x + \".jpg');\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//依解析度改位置\r\n");
      out.write("\t\t\tvar w = (screen.width - 450)/2-40;\r\n");
      out.write("\t\t\tdocument.getElementById( \"titleD\" ).setAttribute(\"style\", \"margin-left:\" + w + \"px;\");\r\n");
      out.write("\t\t\t//生標題div   addQ()\r\n");
      out.write("         }\r\n");
      out.write("\t\t \r\n");
      out.write("         window.addEventListener( \"load\", start, false );\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //回到最上層\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t//動畫方式回到上層\r\n");
      out.write("\t\t$(\"#gotopD\").click(function(){\r\n");
      out.write("\t\t\tjQuery(\"html,body\").animate({scrollTop:0},300);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//目前的位置距離網頁頂端，若大於300px則顯示回上層圖示;否則隱藏\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tif ( $(this).scrollTop() > 500){\r\n");
      out.write("\t\t\t\t$('#gotopD').fadeIn(\"fast\");\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\t$('#gotopD').stop().fadeOut(\"fast\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("      </script>\r\n");
      out.write("\t  <style>\r\n");
      out.write("\t\tbody\t{\r\n");
      out.write("\t\t\t\t\tfont-family: Helvetica, Microsoft YaHei, LiHei Pro, TW-Kai;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*搜尋Div*/\r\n");
      out.write("\t\t#titleD {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\t\ttop: 1%;\r\n");
      out.write("\t\t\t\t\twidth: 450px;\r\n");
      out.write("\t\t\t\t\theight: 200px;\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("\t\t\t\t\tpadding: 5px 5px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 20px;  /*圓角*/\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*中間Div*/\r\n");
      out.write("\t\t.contentDiv {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\tleft: 20%;\r\n");
      out.write("\t\t\t\t\twidth: 55%;\r\n");
      out.write("\t\t\t\t\theight: 160px;\r\n");
      out.write("\t\t\t\t\tmargin-bottom: 50px;\r\n");
      out.write("\t\t\t\t\tbackground-color: #FFFFFF; \r\n");
      out.write("\t\t\t\t\tbox-shadow:4px 3px 2px 1px black;\r\n");
      out.write("\t\t\t\t\tpadding: 5px 5px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDDT {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop:3%;\r\n");
      out.write("\t\t\t\t\tleft:4%;\r\n");
      out.write("\t\t\t\t\twidth:98%;\r\n");
      out.write("\t\t\t\t\theight: 35px;\r\n");
      out.write("\t\t\t\t\tfont-size: 30px;\r\n");
      out.write("\t\t\t\t\tcolor: blue;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.contentDDC {\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\tmargin-top:30px;\r\n");
      out.write("\t\t\t\t\tleft:3%;\r\n");
      out.write("\t\t\t\t\twidth: 98%;\r\n");
      out.write("\t\t\t\t\theight: 55%;\r\n");
      out.write("\t\t\t\t\tfont-size: 15px;\r\n");
      out.write("\t\t\t\t\tcolor: gray;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t    #enterP {\r\n");
      out.write("\t\t            position: relative;\r\n");
      out.write("\t\t\t\t\tmargin-top:20px;\r\n");
      out.write("\t\t\t\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t/*上圖*/\r\n");
      out.write("\t\t.background1  {\r\n");
      out.write("\t\t\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\t\t\tbackground-attachment: scroll;\r\n");
      out.write("\t\t\t\t\tposition: absolute;\r\n");
      out.write("\t\t\t\t\ttop: 0%;\r\n");
      out.write("\t\t\t\t\tleft: 0%;\r\n");
      out.write("\t\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\t\theight: 40%;\r\n");
      out.write("\t\t\t\t\tz-index: -998;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t/*中下底*/\r\n");
      out.write("\t\t.background2 {\r\n");
      out.write("\t\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\t\ttop: 0%;\r\n");
      out.write("\t\t\t\t\tleft: 0%;\r\n");
      out.write("\t\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\t\tz-index: -999;\r\n");
      out.write("\t\t\t\t\tbackground-color: rgba(62, 173, 97, 0.63);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#gotopD {\r\n");
      out.write("\t\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\t\ttop: 92%;\r\n");
      out.write("\t\t\t\t\tleft: 90%;\r\n");
      out.write("\t\t\t\t\theight: 20px;\r\n");
      out.write("\t\t\t\t\twidth: 22px;\r\n");
      out.write("\t\t\t\t\tmargin-right: 200px;\r\n");
      out.write("\t\t\t\t\tbackground: rgba(0, 0, 0, 0.6);\r\n");
      out.write("\t\t\t\t\tpadding: 10px 20px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;  /*圓角*/\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t#gotopP {\r\n");
      out.write("\t\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\t\tcolor: white;\r\n");
      out.write("\t\t\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.options {\r\n");
      out.write("\t\t\t\t\tmargin-top: 20px;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t.clabel:hover {\r\n");
      out.write("\t\t            cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#titleP {\r\n");
      out.write("\t\t\t\t\tmargin-top: 50px;\r\n");
      out.write("\t\t\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t  </style>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("\t<div id = \"image\" class = \"background1\"></div>\r\n");
      out.write("\t<div class = \"background2\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--草之擺標題-->\r\n");
      out.write("\t<div id = \"titleD\">\r\n");
      out.write("\t    <p id = \"titleP\" align = \"center\">\r\n");
      out.write("\t        ");

		        Polls h = (Polls) request.getAttribute("pollWillAnswer");
			    out.print(h.getTitle());
		    
      out.write("\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  \r\n");
      out.write("\t<p align = \"center\" style = \"position: absolute; top: 30%; left: 6%; width: 50px; height: 50px;\"><input type = \"button\" value = \"測試新增Q\" onclick = \"test()\"></p>\r\n");
      out.write("\t-->\r\n");
      out.write("\t<!--草之擺題目-->\r\n");
      out.write("\t<div id = \"ContentDiv\">\r\n");
      out.write("        \r\n");
      out.write("\t\t");

		    Polls a = (Polls) request.getAttribute("pollWillAnswer");
			ArrayList<Question> Q = a.getQuestionList();
			int distance = 0;
			int count = 0;
			int countt = 0;
			int plus_H = 0;
			int basic_H = 160;
			int aDD = 40;
			int question_H = 0;
			int button_T = 0;
			int option_C = 0;
			int i = 0;
			ArrayList<String> options;
			
			for(Question q : Q)
			{
			    out.print("<form action = 'AnswerServlet?id=" + a.getID() + "' method ='post'>");

				distance = 300 + (200 + 5) * count + plus_H;
				options = q.getOptionList();
				option_C = options.size();
				question_H = basic_H;
				
				if(option_C > 3)
				{
					question_H += (option_C - 3) * aDD;
					plus_H += (option_C - 3) * aDD;
				}
				
				out.print("<div class = 'contentDiv' style = 'top : " + distance + "px; height: " + question_H + "px;'><div class ='contentDDT'>" + q.getQuestion() + "</div><div class='contentDDC'>");
				
				countt = 0;
				for(String d : options)
			    {
				    out.print("<input class = 'options' type='radio' id=" + count + countt + " name=" + count + " value=" + countt );
					if(countt == 0)
					{
						out.print(" checked='checked'");
					}
					out.print("><label for=" + count + countt + " class='clabel'>&nbsp;" + d + "</label><br>");
					countt++;
			    }
			    out.print("</div></div>");
				count++;
			}
			button_T += distance + question_H;
			button_T += 20;
			out.print("<p id = 'enterP'  style = 'top: " + button_T + "px; magrin-bottom: 30px;' align = 'center'><input type='submit' name='button' id='button' value='送出' /></p></form>");
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"gotopD\" href = \"#top\" hidden = \"true\">\r\n");
      out.write("\t\t<a href = \"#top\" id = \"gotopP\">Top</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
