/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2018-06-21 03:46:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;

public final class showReward_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Reward 好爽哦!</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("        .itemImg{\r\n");
      out.write("            width:200px;\r\n");
      out.write("            height:80px;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            right:250px;\r\n");
      out.write("        }\r\n");
      out.write("        .itemText{\r\n");
      out.write("            font-size:26px;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            right:80px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("          width:100px;\r\n");
      out.write("          height:80px;\r\n");
      out.write("     \t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t <table align=\"center\">\r\n");
      out.write("        <tr style=\"font-size:22px; text-decoration:underline;\">\r\n");
      out.write("            <td style=\"position:relative; right:180px;\"> 物 品 圖 片</td>\r\n");
      out.write("            <td> 物 品 名 稱</td>\r\n");
      out.write("            <td> 兌 換 序 號</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("       \t");

		int reward1 = (Integer)request.getAttribute("reward1");
   		int reward2 = (Integer)request.getAttribute("reward2");
   		int reward3 = (Integer)request.getAttribute("reward3");
   		String tag = "";
       		String[] alphaStr = {"0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
       		for(int i=0;i<reward1;i++)
       		{
       			tag = "";
       			for(int j=0;j<20;j++)
       			{
       				tag += alphaStr[(int) (Math.random()*36)];
       			}
       			out.print("<tr><td><img src='mmm.jpg' class='itemImg' /></td><td class='itemText'> 麥當勞套餐兌換卷</td><td>"+ tag + "</td></tr>");
       		}
       		for(int i=0;i<reward2;i++)
       		{
       			tag = "";
       			for(int j=0;j<20;j++)
       			{
       				tag += alphaStr[(int) (Math.random()*36)];
       			}
       			out.print("<tr><td><img src='startbark.jpg' class='itemImg' /></td><td class='itemText'> 星巴克咖啡類兌換卷</td><td>" + tag + "</td></tr>");
       		}
       		for(int i=0;i<reward3;i++)
       		{
       			tag = "";
       			for(int j=0;j<20;j++)
       			{
       				tag += alphaStr[(int) (Math.random()*36)];
       			}
       			out.print("<tr><td><img src='711shopping.png' class='itemImg' /></td><td class='itemText'> 7-11購物金50元</td><td>" + tag + "</td></tr>");
       		}
       	
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    <form action=\"exchangePage.jsp\">\r\n");
      out.write("    \t<input type=\"submit\" value=\"確定\" class=\"btn\" >\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
